/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.WisataData;


/**
 *
 * @author djavu
 */
public class Home extends javax.swing.JFrame {

    class ImageRenderer extends DefaultTableCellRenderer {

        JLabel lbl = new JLabel();

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            lbl.setIcon((ImageIcon) value);
            return lbl;
        }
    }

    //deklarasi tabel model
    DefaultTableModel tbl = new DefaultTableModel();

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_beli = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_pembeli = new javax.swing.JMenu();
        menu_exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Wisata", "Nama Wisata", "Deskripsi", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        btn_beli.setBackground(new java.awt.Color(51, 153, 255));
        btn_beli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_beli.setForeground(new java.awt.Color(255, 255, 255));
        btn_beli.setText("BELI");
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });

        menu_pembeli.setText("Data Pembeli");
        menu_pembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_pembeliMousePressed(evt);
            }
        });
        jMenuBar1.add(menu_pembeli);

        menu_exit.setText("Exit");
        menu_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_exitMouseReleased(evt);
            }
        });
        jMenuBar1.add(menu_exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btn_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        Image image = null;
        WisataData wisata = new WisataData();
        int size = wisata.getArraySize();
        try {

            tabel.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
            tbl = (DefaultTableModel) tabel.getModel();
            tabel.setRowHeight(150);
            for (int i = 0; i < size; i++) {
                URL url = new URL(wisata.getUrlImage().get(i));
//                image = ImageIO.read(url);

                ImageIcon imggg = new ImageIcon(new ImageIcon(url).getImage()
                        .getScaledInstance(150, 150, Image.SCALE_SMOOTH));

                tbl.addRow(new Object[]{imggg, wisata.getNamaWisata().get(i), wisata.getDescWisata().get(i), wisata.getHarga().get(i)});
            }

            tabel.setModel(tbl);

        } catch (IOException e) {
            e.printStackTrace();

        }


    }//GEN-LAST:event_formComponentShown

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed

        if (tabel.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih dulu");
        } else {
            WisataData wisata = new WisataData();
            int index = tabel.getSelectedRow();
            String namaWisata = wisata.getNamaWisata().get(index);
            String image = wisata.getUrlImage().get(index);
            String hrg = wisata.getHarga().get(index);

            DetailTiket detail = new DetailTiket(namaWisata, hrg, image);
            detail.setVisible(true);

        }


    }//GEN-LAST:event_btn_beliActionPerformed

    private void menu_pembeliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_pembeliMousePressed
       DataPembeli dataPembeli = new DataPembeli();
       dataPembeli.setVisible(true);
    }//GEN-LAST:event_menu_pembeliMousePressed

    private void menu_exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_exitMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_exitMouseReleased

    private void menu_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_menu_exitMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_beli;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_exit;
    private javax.swing.JMenu menu_pembeli;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
